apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.api.name }}
data:
  properties.ini: |
    database="{{ .Values.bdd.name }}:3306"
    dbpassword="{{ .Values.bdd.user.password }}"
    dbuser="{{ .Values.bdd.user.name }}"
    dbname="{{ .Values.bdd.schema }}"