# Default values for demo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

bdd:
  name: mariadb
  schema: lab
  user:
    name: admin
    password: Ecam123!

api:
  name: api

web:
  name: web